---
- name: npm install badgekit api dependencies
  npm: path={{ API_INSTALL_LOCATION }} state=present executable=/usr/local/n/versions/node/0.10.33/bin/npm
- name: npm install badgekit admin dependencies
  npm: path={{ ADMIN_INSTALL_LOCATION }}/admin state=present executable=/usr/local/n/versions/node/0.10.33/bin/npm
- name: migrate badgekit api db
  shell: /usr/local/n/versions/node/0.10.33/bin/node {{ API_INSTALL_LOCATION }}/bin/db-migrate up
  when: API_LOCAL_INSTALL == True
  environment:
    DB_HOST: "{{ DB_HOST }}"
    DB_NAME: "{{ DB_NAME }}"
    DB_PASSWORD: "{{ DB_PASSWORD }}"
    DB_USER: "{{ DB_USER }}"
    MASTER_SECRET: "{{ MASTER_SECRET }}"
    PORT: "{{ API_PORT }}"
    NODE_ENV: "{{ NODE_ENV }}"
- name: migrate badgekit admin db
  shell: /usr/local/n/versions/node/0.10.33/bin/node {{ ADMIN_INSTALL_LOCATION }}/bin/db-migrate up
  when: ADMIN_LOCAL_INSTALL == True
  environment:
    COOKIE_SECRET: "{{ COOKIE_SECRET }}"
    PORT: "{{ ADMIN_PORT }}"
    OPENBADGER_SYSTEM: "{{ OPENBADGER_SYSTEM }}"
    OPENBADGER_URL: "{{ OPENBADGER_URL }}"
    OPENBADGER_SECRET: "{{ OPENBADGER_SECRET }}"
    DATABASE_DRIVER: "{{ DATABASE_DRIVER }}"
    DATABASE_HOST: "{{ DATABASE_HOST }}"
    DATABASE_USER: "{{ DATABASE_USER }}"
    DATABASE_PASSWORD: "{{ DATABASE_PASSWORD }}"
    DATABASE_DATABASE: "{{ DATABASE_DATABASE }}"
    PERSONA_AUDIENCE: "{{ PERSONA_AUDIENCE }}"
    API_SECRET: "{{ API_SECRET }}"
    BRANDING: "{{ BRANDING }}"
    NODE_TLS_REJECT_UNAUTHORIZED: "{{ NODE_TLS_REJECT_UNAUTHORIZED }}"
